CSCQVAIN-208: Add License URL oneOf
CSCfi/qvain-js pull request #45
Opened 2019-07-01 09:24 UTC by Kauhia

Note: likely breaks default license implementation

2019-07-01 12:04 UTC, jppiiroinen requested changes
what " likely breaks default license implementation" means in this case?

2019-07-01 12:21 UTC, Kauhia commented
It means that the default values won't anymore be placed correctly on reference data component creation due to path changes. There is replacement implementation in https://github.com/CSCfi/qvain-js/pull/39 but even it needs a small tweak to work with this PR. I think it should be merged first and then I can update this so that it doesn't break the default license value.

2019-07-02 07:53 UTC, jppiiroinen commented
#39 has been approved

2019-07-11 08:00 UTC, jppiiroinen approved these changes

2019-07-11 08:06 UTC, merged